### ISSUE TITLE
Column 65 is repeated on column 1 

### ISSUE THREAD

**Issue by FrenchLab47** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#1]
Hello,

I am testing your DMA library, and I am very surprised by the result.
The color management is superior to other libraries, and the flickerings are really reduced.

I find just a small display defect that I can not correct myself, but maybe you have an idea.

When drawing a text or rectangle smaller than the width of the LED panel (less than 64 pixels) the text or drawing is displayed correctly.
But if the text or drawing is larger than the panel, or shifted to the right, the contents of column 65 (which should not be visible) are superimposed on column 1.
This defect is also very visible and annoying if you scroll through the text.

Thank you for telling me if you have a solution, and thank you very much for your work.
Best Regards.
P.B.

**Comment by FrenchLab47** [comment]
Finally I solved this repetition problem by adding "=" signs in line 179 of the file ESP32-RGB64x32MatrixPanel-I2S-DMA.cpp
like this :
    // Need to check that the co-ordinate is within range, or it'll break everything big time.
    if ( x_coord < 0 || y_coord < 0 || x_coord >= MATRIX_WIDTH || y_coord >= MATRIX_HEIGHT)

**Comment by mrfaptastic** [comment]
Hello P.B.

Thank you so very much for using this library (that's two of us now), and for finding the solution to this bug. I have replaced the code with your fix.

The vast majority of the credit/code for this library can be attributed to Louis Beaudoin (https://github.com/pixelmatix/esp32_I2sParallelDmaLedMatrix) and some person by the name of Sprite_TM(https://www.esp32.com/viewtopic.php?f=17&t=3188).  I re-purposed it to be usable with the Adafruit library, which many people use.
