### ISSUE TITLE
Question about using ESP32

### ISSUE THREAD

**Issue by FleaCatcher** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#10]
Your readme.md is extensive; thank you. 
I do have a few questions:
1. what type of ESP32 board are you using, and does it matter?
2. I don't see any level shifters, are they needed?

3. Is your assignment of I/O pins anything other than 'random' ?
Would it theoretically work if alternates were used?
Your readme.md refers to  (defaults defined in ESP32-RGB64x32MatrixPanel-I2S-DMA.h).
/* ESP32 Pin Definition. You can change this, but best if you keep it as is...  

the above are the questions I hoped you could answer.
If you are interested, here are more details about the alternate pin order
--------------------------

4.  I would like to use an Adafruit RGB Matrix Featherwing  kit 
https://www.adafruit.com/product/3036
https://learn.adafruit.com/assets/59625

RGB  MR.FAP	 ADAFRUIT
R1  -> IO25     IO32
G1  -> IO26	IO14
B1  -> IO27	IO15
R2  -> IO14	IO27
G2  -> IO12	IO33
B2  -> IO13	IO12
A   -> IO23     IO 4
B   -> IO22	IO36
C   -> IO 5     IO39
D   -> IO17	IO34
CLK -> IO16     IO13
LAT -> IO 4	IO16
OE  -> IO15     IO17

Here is your original list of #defines

/* ESP32 Pin Definition. You can change this, but best if you keep it as is...  

#define R1_PIN_DEFAULT  25	
#define G1_PIN_DEFAULT  26
#define B1_PIN_DEFAULT  27
#define R2_PIN_DEFAULT  14
#define G2_PIN_DEFAULT  12
#define B2_PIN_DEFAULT  13

#define A_PIN_DEFAULT   23
#define B_PIN_DEFAULT   19
#define C_PIN_DEFAULT   5
#define D_PIN_DEFAULT   17
#define E_PIN_DEFAULT   -1 // Change to a valid pin if using a 64 pixel row panel.
          
#define LAT_PIN_DEFAULT 4
#define OE_PIN_DEFAULT  15

#define CLK_PIN_DEFAULT 16

//-----------------------------------------------------//

Here is my replace list of #defines

#define R1_PIN_DEFAULT  32
#define G1_PIN_DEFAULT  14
#define B1_PIN_DEFAULT  15
#define R2_PIN_DEFAULT  27
#define G2_PIN_DEFAULT  33
#define B2_PIN_DEFAULT  12

#define A_PIN_DEFAULT   4
#define B_PIN_DEFAULT   36
#define C_PIN_DEFAULT   39
#define D_PIN_DEFAULT   34
#define E_PIN_DEFAULT   -1 // Change to a valid pin if using a 64 pixel row panel.

#define LAT_PIN_DEFAULT 16
#define OE_PIN_DEFAULT  17

#define CLK_PIN_DEFAULT 13

**Comment by mrfaptastic** [comment]
Hi FleaCather,

> 1. what type of ESP32 board are you using, and does it matter?

https://wiki.wemos.cc/products:d32:d32

I can't vouch for any other board so I don't know if they'll work or not.

> 2. I don't see any level shifters, are they needed?

Not needed. You don't need level shifters when only 'reading' the output from the ESP32 only. 

> 3. Is your assignment of I/O pins anything other than 'random' ?
> Would it theoretically work if alternates were used?

The wiring I have was the cleanest for _me_ from a physical wiring perspective (i.e. I made it so pins on the left side of the RGB matrix connector, connected to the left side of the D32. And the same for the right side). You can set the pin assignments to whatever you want within the limits of the ESP32.

HOWEVER, you need to be aware that GPIO pads 34 and above (VP, VN, RS etc) are input-only! So stick to pin numbers less than 34.

> #define B_PIN_DEFAULT 36
> #define C_PIN_DEFAULT 39
> #define D_PIN_DEFAULT 34

This doesn't make sense. Pin 39 doesn't even exist? Stick to GPIO's numbers below 34.

https://wiki.wemos.cc/_media/products:d32:sch_d32_v1.0.0.pdf
