### ISSUE TITLE
Green boogies!

### ISSUE THREAD

**Issue by csloz** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#12]
Currently get some mild green "boogies" - spurious extra output in green - issue is described here - 
https://forums.adafruit.com/viewtopic.php?f=47&t=47243#p239274
and
https://www.esp32.com/viewtopic.php?f=17&t=3188&start=30#p22401

Possible to implement any of the changes noted in the code?

**Comment by mrfaptastic** [comment]
Hello. I will take a look when I get time. I'm not sure exactly what has been changed to reduce the ghosting.
