### ISSUE TITLE
Ghosting 2 pixels to the right

### ISSUE THREAD

**Issue by jamesdawson3** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#14]
@mrfaptastic Any thoughts on where to start troubleshooting why I would be getting ghosting 2 pixels shifted to the right (see image)?  I'm using PanelGFXDemo pretty much stock except for changing the pinouts to match my wiring:

```
#define R1_PIN_DEFAULT  15
#define G1_PIN_DEFAULT  2
#define B1_PIN_DEFAULT  0
#define R2_PIN_DEFAULT  4
#define G2_PIN_DEFAULT  16
#define B2_PIN_DEFAULT  17

#define A_PIN_DEFAULT   5
#define B_PIN_DEFAULT   18
#define C_PIN_DEFAULT   19
#define D_PIN_DEFAULT   21
#define E_PIN_DEFAULT   -1
          
#define LAT_PIN_DEFAULT 3
#define OE_PIN_DEFAULT  23

#define CLK_PIN_DEFAULT 22
```

Any thoughts/ideas you have would be much appreciated!

![IMG_5838](https://user-images.githubusercontent.com/14186976/60139862-276e0400-9775-11e9-9d8f-ca02826398a0.JPG)

**Comment by mrfaptastic** [comment]
Hello. Are you able to test with an alternative wiring? I have a panel with the following wiring and no ghosting issues at all. I'm not sure if there's some weird electrical interference occuring due to the pin mapping.

```
#define R1_PIN 25
#define G1_PIN 26
#define B1_PIN 27
#define R2_PIN 14
#define G2_PIN 12
#define B2_PIN 13
#define A_PIN 23
#define B_PIN 19 // Changed from library default
#define C_PIN 5
#define D_PIN 17
#define E_PIN -1
#define LAT_PIN 4
#define OE_PIN 15
#define CLK_PIN 16
```
