### ISSUE TITLE
Wrong wiring guide

### ISSUE THREAD

**Issue by happyme531** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#15]
The wiring guide in the README.md have the following:

` HUB 75 PANEL              ESP 32 PIN
+-----------+   
|  R1   G1  |    R1  -> IO25      G1  -> IO26
|  B1   GND |    B1  -> IO27
|  R2   G2  |    R2  -> IO14      G2  -> IO12
|  B2   GND |    B2  -> IO13
|   A   B   |    A   -> IO23      B   -> IO22
|   C   D   |    C   -> IO 5      D   -> IO17
| CLK   LAT |    CLK -> IO16      LAT -> IO 4
|  OE   GND |    OE  -> IO15      GND -> ESP32 GND
+-----------+

`
The pin B is connected to pin 22
But in the ESP32-RGB64x32MatrixPanel-I2S-DMA.h:

`
#define R1_PIN_DEFAULT  25
#define G1_PIN_DEFAULT  26
#define B1_PIN_DEFAULT  27
#define R2_PIN_DEFAULT  14
#define G2_PIN_DEFAULT  12
#define B2_PIN_DEFAULT  13

#define A_PIN_DEFAULT   23
#define B_PIN_DEFAULT   19
#define C_PIN_DEFAULT   5
#define D_PIN_DEFAULT   17
#define E_PIN_DEFAULT   -1 // Change to a valid pin if using a 64 pixel row panel.
          
#define LAT_PIN_DEFAULT 4
#define OE_PIN_DEFAULT  15

#define CLK_PIN_DEFAULT 16

`
The pin B is connected to pin 19 now.

(And, after finding the problem, I successfully get this library running perfectly on my 32x16 led matrix,just changing the matrix height and width and change the pin E into -1 in the library header file.)

**Comment by mrfaptastic** [comment]
I have updated the README, sorry for the confusion.
