### ISSUE TITLE
add in color333

### ISSUE THREAD

**Issue by csloz** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#16]
Too lazy to do a pull request.

Can you add in Color333 support also in  ESP32-RGB64x32MatrixPanel-I2S-DMA.h 

// Promote 3/3/3 RGB to Adafruit_GFX 5/6/5    RRRrrGGGgggBBBbb
   uint16_t Color333(uint8_t r, uint8_t g, uint8_t b) {  return ((r & 0x7) << 13) | ((r & 0x6) << 10) |         ((g & 0x7) <<  8) | ((g & 0x7) <<  5) |         ((b & 0x7) <<  2) | ((b & 0x6) >>  1);}

**Comment by mrfaptastic** [comment]
Copy pasted into library.
