### ISSUE TITLE
More than 2 displays

### ISSUE THREAD

**Issue by Spindlerkoo** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#18]
Hi,
how many 64x32 RGB displays can your library control?

Thanks, Adam

**Comment by mrfaptastic** [comment]
It's a hardware limitation opposed to a software one. ESP32 only has a small amount of memory, so you'll be hard pressed to show any more than 64x64 pixels with 24bit RGB.

You could experiment with the color depth etc. However, two chained displays would be the limit. I have updated the readme.

**Comment by Spindlerkoo** [comment]
And which memory? Flash or SRAM?

**Comment by mrfaptastic** [comment]
SRAM

**Comment by Spindlerkoo** [comment]
And will this help? https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/external-ram.html

**Comment by mrfaptastic** [comment]
I can't say as I have never used such a thing. Feel free to try it out and report back.

**Comment by mrfaptastic** [comment]
Hi,

I just had a read of the link you posted, and it says under the 'Restrictions' section:

> External RAM cannot be used as a place to store DMA transaction descriptors or as a buffer for a DMA transfer to read from or write into. Any buffers that will be used in combination with DMA must be allocated using heap_caps_malloc(size, MALLOC_CAP_DMA) and can be freed using a standard free() call.

So you will not be able to use this.
