### ISSUE TITLE
drawIcon

### ISSUE THREAD

**Issue by csloz** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#19]
Another small function for the library. 
Could I get commit access?

void drawIcon (int *ico, int16_t x, int16_t y, int16_t cols, int16_t rows);

inline void RGB64x32MatrixPanel_I2S_DMA::drawIcon (int *ico, int16_t x, int16_t y, int16_t cols, int16_t rows) {
  int i, j;
  for (i = 0; i < rows; i++) {
    for (j = 0; j < cols; j++) {
      drawPixelRGB565 (x + j, y + i, ico[i * cols + j]);
    }
  }  
}

**Comment by mrfaptastic** [comment]
Sounds good. Check your email.

**Comment by mrfaptastic** [comment]
I think you forgot to commit the function body as well. I only see the prototype.

**Comment by csloz** [comment]
Its there. -  Line 327

**Comment by mrfaptastic** [comment]
Apologies. You did, not sure how I missed that.

As for bounds checking it's not really required as in lines 181-185 of ESP32-RGB64x32MatrixPanel-I2S-DMA.cpp will catch anything dubious.
