### ISSUE TITLE
Animations can look bad on video to refresh sync mismatch between camera and panel

### ISSUE THREAD

**Issue by huukhoa1412** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#27]
I use your library ESP32-RGB64x32MatrixPanel-I2S-DMA to play Gif Animations

**Comment by mrfaptastic** [comment]
Play with various values for  .setMinRefreshRate(XXX) before doing .begin(....)

**Comment by mrfaptastic** [comment]
https://www.youtube.com/watch?v=wSXqX55R1Gc 

https://www.youtube.com/watch?v=iGYAvxUJZd8

Videos on this topic.

**Comment by huukhoa1412** [comment]
thank to you . i complete

**Comment by mrfaptastic** [comment]
Please note, I have created a new AnimatedGIF example which is better: https://github.com/mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA/tree/master/examples/AnimatedGIFPanel
