### ISSUE TITLE
128x32 RGB Matrix

### ISSUE THREAD

**Issue by ChristophWeiss** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#30]
Hey, i tried to set up a 128x32 matrix but after i uploaded the code it doesnt display the aurora demo or anything else correctly. When im using matrix width at 64 and height at 32 i works correctly and displays on both the same. But width matrix width at 128 and height at 32 it just display`s random pixels
Here is a video:
https://drive.google.com/file/d/16BezRXYpocoWVlfiUOlObM921X3q0c3o/view?usp=sharing

**Comment by mrfaptastic** [comment]
Not sure how I can diagnose.... could be anything Check the wiring, power, try another sketch. Can you run the sketch with SERIAL_DEBUG enabled (refer to the .h file to enable) and print the output here?
