### ISSUE TITLE
Power supply and usb connection

### ISSUE THREAD

**Issue by mtrivolli** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#32]
Sorry if this is not the right place to ask this question. Is it possible to have the ESP32 connected to the computer USB port while powering the matrix with an AC adapter? Should the ESP32 Vin pin be connected to the AC adapter?

Thanks in advance

**Comment by mrfaptastic** [comment]
Technically you can, but you must make sure you have the Grounds connected (aka. GND on ESP32 connected to ground on Matrix) as well!

I miswired this once and nearly melted my laptop's USB port, and fried the ESP32's regulator.
