### ISSUE TITLE
Consider changing the name of the library?

### ISSUE THREAD

**Issue by witnessmenow** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#36]
I wonder does the "64x32" part of the library name put people off using it? I have used it extensively on a 64x64 and have had no issues. I know several people who have used it on 32x16 panels and it has also worked perfectly

Just a suggestion :)

**Comment by sauttefk** [comment]
What about `EPS32-HUB75-MatrixPanel-I2S-DMA`

**Comment by mrfaptastic** [comment]
I could be convinced if it wasn't for issues like #35 and #37. Anybody got any of these panels to understand what the problem could be?

**Comment by Galaxy-Man** [comment]
How about 'TheOneMatrix'?

**Comment by mrfaptastic** [comment]
> What about `EPS32-HUB75-MatrixPanel-I2S-DMA`

I think this is the winner. Not having tested the library myself witha  64x64 panel, I have confidence from others it works ok, so will rename the library and get the arduino folks to update the URL.
