### ISSUE TITLE
64x64 Panel

### ISSUE THREAD

**Issue by csloz** [mrfaptastic/ESP32-RGB64x32MatrixPanel-I2S-DMA#9]
FYI - 

I have tested with a P2.5 64x64 panel with Line E, and H file MATRIX_HEIGHT modified for 64x64

Testing working, and have a plasma test running, but the colors seem slightly different on the left / right side, which looks like image is cut in 2.

I see the code is doing Panel Upper / Panel Lower, will fiddle a little see if I can resolve.

![3291553227471_ pic](https://user-images.githubusercontent.com/3265394/54799998-aa754f00-4c9a-11e9-8f41-7d0a6a8f9ff3.jpg)

**Comment by mrfaptastic** [comment]
Hello. Thanks for testing this out on a 64x64 panel, good to know it works in theory. Can you test with just a single color on the whole display? Red, green or blue? Does this happen with any other libraries? 

Not sure why this would occur. It might be related to #8

**Comment by csloz** [comment]
I have ordered some other panels to test, will see next week if its panel or other issue.

On another note, would be happy to send you a pcb or two that I've made, makes things much easier for interfacing to the ESP32  Let me know via lawrence at computersolutions dot cn, and I'll send you some.

**Comment by csloz** [comment]
Was something funky on that panel, works well on another one. - no color iffyness on bottom.

![WechatIMG1](https://user-images.githubusercontent.com/3265394/54878225-a432ce80-4e64-11e9-8a5b-b76c67a5a400.jpeg)


![WechatIMG2](https://user-images.githubusercontent.com/3265394/54878228-a7c65580-4e64-11e9-91eb-1865f606d12d.jpeg)
